Suppress no javadoc warning
firebolt-db/jdbc pull request #336
Opened 2024-02-04 12:22 UTC by alexradzin

2024-02-05 10:16 UTC, ptiurin requested changes
Merge artefacts present. Please make sure to verify the change before pushing.

2024-02-05 14:18 UTC, ptiurin reviewed
What's the reason for this change? Is it not better to add javadoc where possible?

2024-02-05 15:22 UTC, alexradzin commented
> p

When I run `./gradlew build` I get 100 warnings. Why only 100? Because it is the default limit. Actually it reports about each class, public method and enum value that does not have javadoc. There is no need to write javadoc like "This function performs connection to database" on method `connect()` because it kind of obvious. Javadoc helps to understand the functionality only if it is not obvious from the method/class name otherwise it is annoying. 

I even wanted to write javadocs for all public classes but then I understood that this pointless work will take several days I decided to suppress these warnings so far. However I am going to add javadocs in places where these docs are needed.

2024-02-06 17:57 UTC, ptiurin commented
> When I run `./gradlew build` I get 100 warnings.

Let's try to add the reasoning for a change in the PR description, it helps understanding what's going on without the need to back and forth. I agree having hundreds of warnings is not great and should be fixed.

> Javadoc helps to understand the functionality only if it is not obvious from the method/class name otherwise it is annoying.
> I even wanted to write javadocs for all public classes but then I understood that this pointless work will take several days I decided to suppress these warnings so far.

Let's discuss this on a daily, but I'd add a counterpoint - google's Java coding standards at a minimum require public classes to have javadoc, though they acknowledge that some may not be needed e.g. getFoo() does not need a javadoc saying that this method returns Foo. Perhaps we can suppress on case-by-case basis?

2024-02-07 09:08 UTC, alexradzin commented
> > When I run `./gradlew build` I get 100 warnings.
> 
> Let's try to add the reasoning for a change in the PR description, it helps understanding what's going on without the need to back and forth. I agree having hundreds of warnings is not great and should be fixed.
> 
> > Javadoc helps to understand the functionality only if it is not obvious from the method/class name otherwise it is annoying.
> > I even wanted to write javadocs for all public classes but then I understood that this pointless work will take several days I decided to suppress these warnings so far.
> 
> Let's discuss this on a daily, but I'd add a counterpoint - google's Java coding standards at a minimum require public classes to have javadoc, though they acknowledge that some may not be needed e.g. getFoo() does not need a javadoc saying that this method returns Foo. Perhaps we can suppress on case-by-case basis?

I added PR description

2024-02-13 14:25 UTC, stepansergeevitch approved these changes
Approved, created a JIRA to add javadocs where they're missing: https://packboard.atlassian.net/browse/FIR-30302

2024-02-15 12:41 UTC, merged